# Generated by Django 2.2.5 on 2019-11-24 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roll_call', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='floormanager',
            old_name='floornum',
            new_name='floor_num',
        ),
        migrations.AddField(
            model_name='student',
            name='floor_num',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='roll_call.FloorManager'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='room_num',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('무낟외박', '무단외박'), ('외박', '외박'), ('재실', '재실'), ('퇴사', '퇴사'), ('미입사', '미입사')], default='미입사', max_length=10),
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
